### ISSUE TITLE
Feature: Implement OpenAI's new GPT-3.5-turbo API

### ISSUE THREAD

**Issue by 4y4n** [itsmarsss/KahootGPT#32]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when text-davinci-003 gets the easiest question on my teacher's Kahoot wrong. It is just sad and needs to be updated.

**Describe the solution you'd like**
Implement OpenAI's new chat feature that involves the use of their GPT-3.5-turbo API so that I won't get humiliated in front of my peers

**Describe alternatives you've considered**
I have not considered any alternatives because KahootGPT is supposed to actually win my Kahoot games for me and it does not.

**Additional context**
I hate everything. My feelings are hurt. I can't believe I lost. My teacher thinks I'm an absolute idiot. She walked up to me and said "you are the stupidest student I have ever taught". 

Thank you

**Comment by itsmarsss** [comment]
Working on it

**Comment by itsmarsss** [comment]
Consider it done, will be testing tomorrow; KahootGPT v3.4.x should be released on Chrome Webstore by the end of this week.

You can now choose between `text-davinci-003` and `gpt-3.5-turbo`.

> Additionally, KahootGPT settings have been separated from OpenAI settings. Hence, 2 sections in the config page.

**Comment by itsmarsss** [comment]
Do let me know if you want other `completion` versions on the choice list other than `text-davinci-003`, just as a gimmick. Keep in mind that those versions my not abide to KahootGPT's request to make their reply be in JSON format. (Basically means it may not work)

**Comment by itsmarsss** [comment]
Published to Chrome Webstore, no significant changes in performance.

> Will wait for GPT4 to come out.
