### ISSUE TITLE
Feature: add support to chatgpt-4 turbo preview

### ISSUE THREAD

**Issue by Resha777** [itsmarsss/kahootgpt#38]
please add support to the latest chatgpt 4 as the current one is old and the data is only for September 2022

**Comment by itsmarsss** [comment]
The feature has been added and pushed to the [Chrome Webstore](https://chromewebstore.google.com/detail/kahootgpt-ai-integration/mmnbfkefbancfkmcbfeepiiniggfaobm) (Version 3.7.7)

FYI: this repository does not contain the most up-to-date code
